import { Toaster } from "@/components/ui/sonner";
import { GlobalProvider } from "@/globalcontext/globalcontext";
import { SpeedInsights } from "@vercel/speed-insights/next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "University Question Bank",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Noto+Sans+Bengali:wght@400;700&display=swap"
        />
      </head>
      <body className={inter.className}>
        <SpeedInsights />
        <GlobalProvider>{children} </GlobalProvider>
        <Toaster />
      </body>
    </html>
  );
}
